document:
  name: eIDAS Italian Wallet Technical Specifications
  description: |
    eIDAS Italian Wallet Technical Specifications
  tags:
    - eIDAS
    - eudiw
    - wallet
    - interoperabilità
    - spid
    - cie
    - openid
  
