openapi: 3.0.1
info:
  title: IT Wallet API - AS web services
  version: 0.1.0
servers:
  - url: https://authentic-source.example.it
    description: Authentic Source API
paths:
  /v0.9.0/AttributeClaims/{attribute_type}:
    post:
      tags:
        - e-services PDND
      summary: Get Attribute claims
      description: >-
        This service provides the Credential Issuer with all attribute claims necessary for the issuance of a Digital Credential
      operationId: attributeClaims
      parameters:
        - name: attribute_type
          in: path
          required: true
          description: Identifier of attribute claims set
          schema:
            type: string
            example: PersonIdentificationData
        - name: Authorization
          in: header
          description: >-
            JWT token obtained from <a target="blank"
            href="https://docs.pagopa.it/interoperabilita-1/manuale-operativo/guida-alladesione">PDND
            Interoperabilità.</a><br/><br/><a target="blank"
            href="https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsImtpZCI6ImI4MzlmNGM3LTFlNWQtNGE4YS05ZmM2LTcyZDNiN2YwOTFlYyIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsInN1YiI6IjgyOTE0YjNmLTYwYjItNDUyOS1iNGQ2LTNkNGU2N2YwYTkzMyIsImF1ZCI6Imh0dHBzOi8vZXJvZ2F0b3JlLmV4YW1wbGUvZW50ZS1leGFtcGxlL3YxIiwiZXhwIjoxNzMzMDQyMTUwLCJuYmYiOjE3MzMwNDE5NDUsImlhdCI6MTczMzA0MTkyMCwianRpIjoiYzRmNWQ3ZTItYjdjOC00MGY2LTliNmEtZGM5YTRmNWFlYjU3IiwiY2xpZW50X2lkIjoiODI5MTRiM2YtNjBiMi00NTI5LWI0ZDYtM2Q0ZTY3ZjBhOTMzIiwicHVycG9zZUlkIjoiZDJiOWE2NTMtYzQ5Ny00NWM2LWI4ZjEtNWJkZjEyNGM5ZDNhIiwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiOTkwOGQ5NGI4ZmViMjY4YzAzNzEwNmQ3Yzg5ZTcwNjBjMmNjMWY2YjJiNGViY2I4MDViZmVlNTNhNTM5MzA3YiJ9fQ.9e3dwxSa5fSTPolA2NG7kpa0IEpNY0rM9Wc6cczsKwRlv1fEpKKtjcxnUyRG8fqo5Ajbun_39AqMUqOqCIcCVg">EXAMPLE
            ON JWT.IO</a>
          required: true
          schema:
            type: string
            format: Signed JWT
            example: >-
              DPoP
              eyJhbGciOiJFUzI1NiIsImtpZCI6ImI4MzlmNGM3LTFlNWQtNGE4YS05ZmM2LTcyZDNiN2YwOTFlYyIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsInN1YiI6IjgyOTE0YjNmLTYwYjItNDUyOS1iNGQ2LTNkNGU2N2YwYTkzMyIsImF1ZCI6Imh0dHBzOi8vZXJvZ2F0b3JlLmV4YW1wbGUvZW50ZS1leGFtcGxlL3YxIiwiZXhwIjoxNzMzMDQyMTUwLCJuYmYiOjE3MzMwNDE5NDUsImlhdCI6MTczMzA0MTkyMCwianRpIjoiYzRmNWQ3ZTItYjdjOC00MGY2LTliNmEtZGM5YTRmNWFlYjU3IiwiY2xpZW50X2lkIjoiODI5MTRiM2YtNjBiMi00NTI5LWI0ZDYtM2Q0ZTY3ZjBhOTMzIiwicHVycG9zZUlkIjoiZDJiOWE2NTMtYzQ5Ny00NWM2LWI4ZjEtNWJkZjEyNGM5ZDNhIiwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiOTkwOGQ5NGI4ZmViMjY4YzAzNzEwNmQ3Yzg5ZTcwNjBjMmNjMWY2YjJiNGViY2I4MDViZmVlNTNhNTM5MzA3YiJ9fQ.9e3dwxSa5fSTPolA2NG7kpa0IEpNY0rM9Wc6cczsKwRlv1fEpKKtjcxnUyRG8fqo5Ajbun_39AqMUqOqCIcCVg
        - name: DPoP
          in: header
          description: >-
            DPoP proof JWT, to comply with the REST_JWS_2021_POP security
            pattern. See also <a target="blank"
            href="https://datatracker.ietf.org/doc/html/rfc9449.html">RFC
            9449</a>.<br/><br/>

            <a target="blank" href="https://jwt.io/#debugger-io?token=eyJ0eXAiOiJkcG9wK2p3dCIsImFsZyI6IkVTMjU2IiwiandrIjp7Imt0eSI6IkVDIiwia2V5X29wcyI6WyJzaWduIl0sImtpZCI6ImRGVTNNRDI4REpfamZzZmloUHZpMm8tQ3RqTEVVejNwT0lWMEJkTk1mZjgiLCJjcnYiOiJQLTI1NiIsIngiOiJodXlYSVFOdjkwMm9Mc3BYNF96b25DOTRHNnlFbG42bHNkbS0xd003MzJvIiwieSI6Ikk5UERFYXdXSHFhRkRHeDFaa05rLTJQVjZXZHBjYUgzQWZPYkJTTGloZ3cifX0.eyJqdGkiOiItQndDM0VTYzZhY2MybFRjIiwiaHRtIjoiUE9TVCIsImF0aCI6ImM1MmMzZTU4MmNjYTRhZTgyYTRhYWRjODA3MTIwZGZmODRlNmIzYjA5MTg3NjMwMmYxY2QyN2I0ODRmNmE1YjgiLCJodHUiOiJodHRwczovL3NlcnZlci5leGFtcGxlLmNvbS90b2tlbiIsImlhdCI6MTc2MjI2MjYxNn0.C--7xxs9hbF6eA6HM9gGvQ1FtlseiJ9hYFAsMnAsu-JtlzNXJXoAvrVOVkeYtkQ6beXveOern56_rLDoR4gmiw">EXAMPLE
            ON JWT.IO</a>
          required: true
          schema:
            type: string
            format: JWT
            example: >-
              eyJ0eXAiOiJkcG9wK2p3dCIsImFsZyI6IkVTMjU2IiwiandrIjp7Imt0eSI6IkVDIiwia2V5X29wcyI6WyJzaWduIl0sImtpZCI6ImRGVTNNRDI4REpfamZzZmloUHZpMm8tQ3RqTEVVejNwT0lWMEJkTk1mZjgiLCJjcnYiOiJQLTI1NiIsIngiOiJodXlYSVFOdjkwMm9Mc3BYNF96b25DOTRHNnlFbG42bHNkbS0xd003MzJvIiwieSI6Ikk5UERFYXdXSHFhRkRHeDFaa05rLTJQVjZXZHBjYUgzQWZPYkJTTGloZ3cifX0.eyJqdGkiOiItQndDM0VTYzZhY2MybFRjIiwiaHRtIjoiUE9TVCIsImF0aCI6ImEyMWQxMzUzZGYwZTExOTQ4ODE1NDAwZGU2MjUxYzUwNjlhYTFhNjBjMDg5YWViYTQ2MTI1Y2JlNjhmNzQ1ZmYiLCJodHUiOiJodHRwczovL3NlcnZlci5leGFtcGxlLmNvbS90b2tlbiIsImlhdCI6MTc2MjI2MjYxNn0.bVf2E4qvHTNGAGXPNcOLrgI_QcXmx0k8Ays6d6gPuT6X1Pbwzz_ltYBxiT28O8ab2-ulk9Rg8TIHOG_H5ZCCSA
        - name: Agid-JWT-Signature
          in: header
          description: >-
            JWT containing the signature of the message headers whose integrity
            needs to be guaranteed, to comply with the INTEGRITY_REST_02
            security pattern. <a target="blank"
            href="https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/e-service-pdnd.html">e-Service PDND</a>. <br/><br/>

            <a target="blank" href="https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjA5NzlmN2NhYjllZWZlMGMyYjQ0ZTY5MjUwN2Y3OWY3IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsInN1YiI6IjgyOTE0YjNmLTYwYjItNDUyOS1iNGQ2LTNkNGU2N2YwYTkzMyIsImF1ZCI6Imh0dHBzOi8vZXJvZ2F0b3JlLmV4YW1wbGUvZW50ZS1leGFtcGxlL3YxIiwiZXhwIjoxNzgzMDQyMTUwLCJuYmYiOjE3MzMwNDE5NDUsImlhdCI6MTczMzA0MTkyMCwianRpIjoiYzRmNWQ3ZTItYjdjOC00MGY2LTliNmEtZGM5YTRmNWFlYjU3IiwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiOTkwOGQ5NGI4ZmViMjY4YzAzNzEwNmQ3Yzg5ZTcwNjBjMmNjMWY2YjJiNGViY2I4MDViZmVlNTNhNTM5MzA3YiJ9fQ.vKPFFX8W4INWVDMSvgpsBd-FUnVhB40DQtfJxUgNQIMzs_D7k314fVyMygsnMnh2ulgZx0v5uR4w4A72-DcOQA">EXAMPLE
            ON JWT.IO</a>
          required: true
          schema:
            type: string
            format: JWT
            example: eyJhbGciOiJFUzI1NiIsImtpZCI6IjA5NzlmN2NhYjllZWZlMGMyYjQ0ZTY5MjUwN2Y3OWY3IiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsInN1YiI6IjgyOTE0YjNmLTYwYjItNDUyOS1iNGQ2LTNkNGU2N2YwYTkzMyIsImF1ZCI6Imh0dHBzOi8vZXJvZ2F0b3JlLmV4YW1wbGUvZW50ZS1leGFtcGxlL3YxIiwiZXhwIjoxNzgzMDQyMTUwLCJuYmYiOjE3MzMwNDE5NDUsImlhdCI6MTczMzA0MTkyMCwianRpIjoiYzRmNWQ3ZTItYjdjOC00MGY2LTliNmEtZGM5YTRmNWFlYjU3IiwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiOTkwOGQ5NGI4ZmViMjY4YzAzNzEwNmQ3Yzg5ZTcwNjBjMmNjMWY2YjJiNGViY2I4MDViZmVlNTNhNTM5MzA3YiJ9fQ.vKPFFX8W4INWVDMSvgpsBd-FUnVhB40DQtfJxUgNQIMzs_D7k314fVyMygsnMnh2ulgZx0v5uR4w4A72-DcOQA
        - name: Digest
          in: header
          description: >-
            Digest of the message payload, to comply with the INTEGRITY_REST_02
            security pattern. According to <a target="blank" href="https://www.rfc-editor.org/rfc/rfc3230.html#section-4.2">RFC
            3230 §4.2</a>, the format MUST be the following: digest-algorithm=encoded
            digest output.
          required: true
          schema:
            type: string
            example: SHA-256=b626aa33e25d46086dd5c12b631be51caeece92689912408e96dc4a430f3fa67
        - name: Agid-JWT-TrackingEvidence
          in: header
          description: >-
            JWT containing the data tracker in the Consumer's domain. It is mandatory only when complying with AUDIT_REST_02.
            <a target="blank"
            href="https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/e-service-pdnd.html">e-Service PDND</a>. <br/><br/>

            <a target="blank" href="https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsImtpZCI6IjhlOGRlNGJmZTFlNWVhNzkwM2E1ODE2ZmNlNzNjZDQ4IiwidHlwIjoiSldUIn0.eyJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsImF1ZCI6Imh0dHBzOi8vZXJvZ2F0b3JlLmV4YW1wbGUvZW50ZS1leGFtcGxlL3YxIiwiZXhwIjoxNzgzMDQyMTUwLCJuYmYiOjE3MzMwNDE5NDUsImlhdCI6MTczMzA0MTkyMCwianRpIjoiYzRmNWQ3ZTItYjdjOC00MGY2LTliNmEtZGM5YTRmNWFlYjU3IiwiY2xpZW50X2lkIjoiODI5MTRiM2YtNjBiMi00NTI5LWI0ZDYtM2Q0ZTY3ZjBhOTMzIiwicHVycG9zZUlkIjoiZDJiOWE2NTMtYzQ5Ny00NWM2LWI4ZjEtNWJkZjEyNGM5ZDNhIiwiZG5vbmNlIjoiNjUyODQyNDIxMzY4NSIsInVzZXJJRCI6ImE4YjdjNmQ1LWU0ZjMtZzJoMS1pOWowLWtsbW5vcHFyc3R1diJ9.vHispWBZeWk0UYwUSMAxpioC4giifbctyC3sgiqNxNHt_ypxIr6FZkKlTrLc02WivSm3ApbZ0ABi1RgtcUthYQ">EXAMPLE
            ON JWT.IO</a>
          required: true
          schema:
            type: string
            format: JWT
            example: eyJhbGciOiJFUzI1NiIsImtpZCI6IjhlOGRlNGJmZTFlNWVhNzkwM2E1ODE2ZmNlNzNjZDQ4IiwidHlwIjoiSldUIn0.eyJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsImF1ZCI6Imh0dHBzOi8vZXJvZ2F0b3JlLmV4YW1wbGUvZW50ZS1leGFtcGxlL3YxIiwiZXhwIjoxNzgzMDQyMTUwLCJuYmYiOjE3MzMwNDE5NDUsImlhdCI6MTczMzA0MTkyMCwianRpIjoiYzRmNWQ3ZTItYjdjOC00MGY2LTliNmEtZGM5YTRmNWFlYjU3IiwiY2xpZW50X2lkIjoiODI5MTRiM2YtNjBiMi00NTI5LWI0ZDYtM2Q0ZTY3ZjBhOTMzIiwicHVycG9zZUlkIjoiZDJiOWE2NTMtYzQ5Ny00NWM2LWI4ZjEtNWJkZjEyNGM5ZDNhIiwiZG5vbmNlIjoiNjUyODQyNDIxMzY4NSIsInVzZXJJRCI6ImE4YjdjNmQ1LWU0ZjMtZzJoMS1pOWowLWtsbW5vcHFyc3R1diJ9.vHispWBZeWk0UYwUSMAxpioC4giifbctyC3sgiqNxNHt_ypxIr6FZkKlTrLc02WivSm3ApbZ0ABi1RgtcUthYQ
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialClaimsRequest'
        required: true
      responses:
        '200':
          description: 200 OK
          content:
            application/jwt:
              schema:
                $ref: '#/components/schemas/CredentialClaimsResponse'
              example: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImE4ZDEzYzQ1ZWYyZTI4MzBmN2M0NGJkNDk0MWNjYSJ9.eyJpc3MiOiJodHRwczovL3ByZC5hcGkuZ2F0ZXdheS5pcHpzLml0L3QvaXR3YWxsZXQuYXBpL3V0aWxpdHktd2FsbGV0LzEuMC4wL3YxL25vdGlmeVN0YXR1c0NyZWRlbnRpYWxzIiwibmJmIjoxNzM2ODQ2Njg4LCJleHAiOjE3MzY4NDY5MjgsImlhdCI6MTczNjg0NjY4OCwiYXVkIjoiMzE2NzAwOTItZWVjMC00Zjk1LTg4ZGEtZTFjN2NlNWU0NTA1IiwianRpIjoiYzhiZDhhMmYtZTk5MC00NGZhLTkwMTMtMWIzNTNiZmM1YTBkIn0.ExthZCx8LHMlTTtBm9qA8Y3FhlKvTl-_sWXq35e_vTRMmKukrLhBhNa-C1xfli8g_JBixYhsBzUWhE0ING_kIQ'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      error:
                        type: string
                        description: invalid_request
                      error_description:
                        type: string
                        description: >-
                          The request cannot be fulfilled because it is missing
                          required parameters, contains invalid parameters, or
                          is otherwise malformed.
                    required:
                      - error
                  - type: object
                    properties:
                      error:
                        type: string
                        description: invalid_dpop_proof
                      error_description:
                        type: string
                        description: >-
                          The request cannot be fulfilled because it contains an
                          invalid dpop proof.
                    required:
                      - error
              examples:
                invalid request:
                  value:
                    error: invalid_request
                    error_description: >-
                      The request cannot be fulfilled because it is missing
                      required parameters, contains invalid parameters, or is
                      otherwise malformed
                invalid dpop proof:
                  value:
                    error: invalid_dpop_proof
                    error_description: >-
                      The request cannot be fulfilled because it contains an
                      invalid dpop proof
        '401':
          description: Unauthorized
          headers:
            WWW-Authenticate:
              description: The request cannot be fulfilled because the Voucher is expired, revoked or otherwise malformed. See <a target="blank" href="https://datatracker.ietf.org/doc/html/rfc6750.html#section-3">RFC6750</a> and <a target="blank" href="https://datatracker.ietf.org/doc/html/rfc9449.html#section-7.1-11">RFC9449</a> for details.
              schema:
                type: string
        '404':
          description: Claims not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error code
                    example: not_found
                  error_description:
                    type: string
                    description: >-
                      Text in human-readable form providing further details to
                      clarify the nature of the error encountered
                    example: >-
                      The authentic source cannot fulfill the request because the
                      claims were not found
                required:
                  - error
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: server_error
                  error_description:
                    type: string
                    description: >-
                      The request cannot be fulfilled because the e-Service Endpoint encountered an internal problem.
                required:
                  - error
              example:
                error: invalid_request
                error_description: >-
                  TThe request cannot be fulfilled because the e-Service Endpoint encountered an internal problem.
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error code
                  error_description:
                    type: string
                    description: >-
                      Text in human-readable form providing further details to
                      clarify the nature of the error encountered
                required:
                  - error
              example:
                error: 'temporarily_unavailable'
                error_description: 'The request cannot be fulfilled because the e-Service Endpoint is temporarily unavailable (e.g., due to maintainance or overload)'
components:
  schemas:
    CredentialClaimsResponse:
      properties:
        Header:
          type: object
          properties:
            alg:
              description: A digital signature algorithm identifier.
              type: string
              example: RS256
            kid:
              description: Unique identifier of the JWK used by the Provider to sign the JWT.
              type: string
              example: 'cdb52532-dd94-40ef-824d-9c55b10e6bc9'
            typ:
              description: It MUST be set to 'JWT'.
              type: string
              example: 'JWT'
          required : [alg, kid, typ]
        Payload:
          type: object
          properties:
            iss:
              description: The identifier of the e-Service.
              type: string
              example: 'https://pre.api.gateway.ipzs.it/t/itwallet.api/utility-wallet/1.0.0/v1/revokeAll'
            aud:
              description: The identifier of the Consumer.
              type: string
              example: '31670092-eec0-4f95-88da-e1c7ce5e4505'
            exp:
              description: UNIX timestamp representing the JWT expiration time.
              type: integer
              example: 1736846928
            iat:
              description: UNIX timestamp representing the JWT issuance time.
              type: integer
              example: 1736846688
            jti:
              description: Unique identifier of the JWT to prevent replay attacks.
              type: string
              example: '8b971b43-e990-44fa-9013-1b353bfc5a0f'
            nbf:
              description: UNIX timestamp representing the JWT first validity time.
              type: string
              example: '1736846688'
            lead_time:
              description: The estimated amount of time (in seconds) required before making the request of the attribute claims again.
              type: integer
              example: '864000'
            claims:
              description: List of Credential Claims.
              type: object
              properties:
                given_name:
                  description:  Current First Name.
                  type: string
                  example: 'Mario'
                family_name:
                  description:  Current Family Name.
                  type: string
                  example: 'Rossi'
                birth_date:
                  description:  Place of Birth.
                  type: string
                  example: 'Roma'
                birth_place:
                  description:  Date of Birth.
                  type: string
                  example: '1980-01-10'
                nationality:
                  description:  Nationality.
                  type: array
                  items:
                    type: string
                  example: 'IT'
                personal_administrative_number:
                  description:  ID ANPR.
                  type: string
                  example: 'XX00000XX'
                tax_id_code:
                  description:  Tax Identification Number.
                  type: string
                  example: 'TINIT-XXXXXXXXXXXXXXXX'
              required: [given_name, family_name, birth_date, birth_place, nationality]               
          required: [iss, aud, exp, iat, jti]
    CredentialClaimsRequest:
      required:
        - unique_id
      type: object
      properties:
        unique_id:
          type: string
          description: ID ANPR or Tax identification number